import type { DayMessages } from '@/types/message'

export const officeMessages: DayMessages[] = [
  {
    daySep: '今天 · 2026年5月23日',
    messages: [
      {
        id: 'o1',
        sender: { type: 'human', name: '安其', avatar: '安', color: '#7a5a3a' },
        time: '09:38',
        html: '@文案Agent 帮我把这周的数据整理成一份内容复盘，我自己存档、也方便对外发刊例。'
      },
      {
        id: 'o2',
        sender: { type: 'bot', name: '文案 Agent', avatar: '文' },
        time: '09:38',
        html: '好的。已从 <code>抖音 / 小红书 / 公众号 / 视频号</code> 自动抓取本周数据，初稿如下，请审阅：',
        doc: {
          title: '安其影视工作室 · 本周内容复盘',
          subtitle: '2026 年第 21 周（5 月 17 日 — 5 月 23 日）· 全平台',
          sections: [
            {
              title: '一、数据概览',
              body: '本周共发布 <b>7 条内容</b>，全平台新增播放 <b>61.2w</b>，净涨粉 <b>+3,180</b>，整体高于上周。',
              table: {
                headers: ['平台', '本周播放', '涨粉', '互动率'],
                rows: [
                  ['抖音',   '42.0w', '+2,140', { text: '5.8%', color: '#6b8e4e' }],
                  ['小红书', '12.6w', '+680',   { text: '7.2%', color: '#6b8e4e' }],
                  ['视频号', '4.8w',  '+210',   { text: '3.1%', color: '#b58932' }],
                  ['公众号', '1.8w',  '+150',   { text: '9.4%', color: '#6b8e4e' }]
                ]
              }
            },
            {
              title: '二、爆款与哑弹',
              body: '<b>爆款：</b>「35 岁职场危机」二创，播放 18.6w，涨粉占本周 60%。<br/><b>哑弹：</b>「副业避坑」完播仅 18%，已定位为前 3 秒钩子偏平，下条优化重发。'
            },
            {
              title: '三、变现',
              body: '本周确认商单 1 单（国货护肤，打包 ¥ 16,000），私域付费咨询 11 单 ¥ 3,300，合计 <b>¥ 19,300</b>。'
            },
            {
              title: '四、下周计划',
              body: '1. 跟进「反内耗」蓝海选题，2 天内出片；<br/>2. 优化「副业避坑」钩子后重发，做 A/B 测试；<br/>3. 私域 2 群启动 3 天话题打卡拉活。'
            }
          ],
          footer: '// generated by 文案 Agent · 2026-05-23 09:38 · v0.3',
          actions: [
            { label: '下载 .docx', primary: true },
            { label: '生成对外刊例' },
            { label: '在画布中编辑' }
          ]
        }
      }
    ]
  }
]
